name: Publish on npm

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
      - name: Generate prerelease version
        run: yarn version --prerelease
      - name: Commit new version
        run: |
          git add .
          git commit -m "chore: bump version [skip ci]"
          git push origin main
      - name: Build version
        run: yarn build
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
